name: Build Gradle Jar Project

on:
  push:
    branches:
      - 'master'
    paths:
      - 'build.gradle'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - 'settings.gradle'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: shadowJar
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PersonalKitten.jar
          path: build/libs/*all.jar